name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin' # Adoptium Temurin을 사용. 다른 배포판을 사용할 경우 여기서 변경 가능

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: demo-jar
          path: build/libs/demo-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: demo-jar
          path: .

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "demo-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/demo-0.0.1-SNAPSHOT.jar"

      - name: SSH and run JAR
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
             ls -a
#            pkill -f 'java -jar' || true
#            nohup java -jar /home/ubuntu/demo-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &